contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - '@local /github/workspace/packages'
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - wolfictl@local

entrypoint:
  command: /usr/bin/wolfictl

command: -h

archs:
  - x86_64
  - aarch64
